### ISSUE TITLE
BUGS: console.error When testing, code that causes React state updates should be wrapped into act()

### ISSUE THREAD

**Issue by TanvirAlam** [FeedAHelp/FeedAHelpless#168]
when running `pnpm run test`

```
feedahelp:test: PASS src/components/ui/features/header/header.test.tsx
feedahelp:test:   ● Console
feedahelp:test:
feedahelp:test:     console.error
feedahelp:test:       Warning: An update to ForwardRef(LoadableComponent) inside a test was not wrapped in act(...).
feedahelp:test:
feedahelp:test:       When testing, code that causes React state updates should be wrapped into act(...):
feedahelp:test:
feedahelp:test:       act(() => {
feedahelp:test:         /* fire events that update state */
feedahelp:test:       });
feedahelp:test:       /* assert on the output */
feedahelp:test:
feedahelp:test:       This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
feedahelp:test:           at useLoadableModule (/Users/tanvir.alam/Projects/FeedAHelpless/node_modules/.pnpm/next@13.4.2_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/src/shared/lib/loadable.tsx:124:5)
feedahelp:test:           at section
feedahelp:test:           at /Users/tanvir.alam/Projects/FeedAHelpless/node_modules/.pnpm/@emotion+react@11.11.1_@types+react@18.2.6_react@18.2.0/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:62:23
feedahelp:test:           at Header
feedahelp:test:
feedahelp:test:       at printWarning (../../node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js:86:30)
feedahelp:test:       at error (../../node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js:60:7)
feedahelp:test:       at warnIfUpdatesNotWrappedWithActDEV (../../node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js:27589:9)
feedahelp:test:       at scheduleUpdateOnFiber (../../node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js:25508:5)
feedahelp:test:       at forceStoreRerender (../../node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js:16977:5)
feedahelp:test:       at handleStoreChange (../../node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js:16953:7)
feedahelp:test:       at callback (../../node_modules/.pnpm/next@13.4.2_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/src/shared/lib/loadable.tsx:236:48)
feedahelp:test:           at Set.forEach (<anonymous>)
feedahelp:test:       at LoadableSubscription.forEach (../../node_modules/.pnpm/next@13.4.2_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/src/shared/lib/loadable.tsx:236:21)
feedahelp:test:       at _update (../../node_modules/.pnpm/next@13.4.2_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/src/shared/lib/loadable.tsx:218:14)
feedahelp:test:
```

**Comment by Rakibs511** [comment]
### **Bug Fixed!**
